name: Web PR Checks

env:
  BUILD_OUTPUT_PATH: apps/web/dist/

defaults:
  run:
    working-directory: .

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

permissions:
  contents: read   # Allows reading repo contents

jobs:
  # Lint check
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup web environment
      uses: ./.github/actions/setup-node-env

    - name: Lint
      run: pnpm lint

  # Run Unit Test & E2E Test
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup web environment
      uses: ./.github/actions/setup-node-env

    - name: Run Test
      run: pnpm test

    - name: Upload e2e test report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: apps/web-e2e/playwright-report/
        retention-days: 30


  # Build check
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup web environment
      uses: ./.github/actions/setup-node-env

    - name: Build
      run: pnpm build